<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Pokemons Play</AssemblyName>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <Version Condition="'$(Version)' == ''">172.0.5</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PKHeX.Core" Version="26.8.26" />
    <EmbeddedResource Include="Assets\Illustrations\adventure-header.png" LogicalName="AdventureHeader" />
    <EmbeddedResource Include="Assets\Fonts\PixelifySans.ttf" LogicalName="PixelifySans" />
    <EmbeddedResource Include="Assets\Consoles\gba.png" LogicalName="ConsoleGba" />
    <EmbeddedResource Include="Assets\Consoles\ds.png" LogicalName="ConsoleDs" />
    <EmbeddedResource Include="Assets\Consoles\3ds.png" LogicalName="Console3ds" />
    <Content Include="Assets\Fonts\OFL.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
